AllCops:
  Exclude:
    - Gemfile.lock
    - Gemfile
    - config/**/*
    - db/**/*

Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/MutableConstant:
  Enabled: false
